<a href="https://colab.research.google.com/github/MadhuraTonpe165/Word_Embedding/blob/main/Embedding_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# BoW- Bag of Words

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

# Sample text data: sentences
corpus = [
    "Python is amazing and fun.",
    "Python is not just fun but also powerful.",
    "Learning Python is fun!",
]

# Initialize the CountVectorizer
vectorizer = CountVectorizer()

# Fit and transform the corpus to a document-term matrix
X = vectorizer.fit_transform(corpus)

# Convert the document-term matrix into a dense format (optional for visualization)
X_dense = X.toarray()

# Get the vocabulary (mapping of words to index positions)
vocab = vectorizer.get_feature_names_out()

# Print the vocabulary and document-term matrix
print("Vocabulary:", vocab)
print("Document-Term Matrix:\n", X_dense)

Vocabulary: ['also' 'amazing' 'and' 'but' 'fun' 'is' 'just' 'learning' 'not'
 'powerful' 'python']
Document-Term Matrix:
 [[0 1 1 0 1 1 0 0 0 0 1]
 [1 0 0 1 1 1 1 0 1 1 1]
 [0 0 0 0 1 1 0 1 0 0 1]]


# TF-IDF

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Sample text data: sentences
corpus = [
    "Python is amazing and fun.",
    "Python is not just fun but also powerful.",
    "Learning Python is fun!",
]

# Create the Tf-idf vectorizer
tfidf_vectorizer = TfidfVectorizer()

# Fit and transform the corpus
X_tfidf = tfidf_vectorizer.fit_transform(corpus)

# Show the Vocabulary
print("Vocabulary:", tfidf_vectorizer.get_feature_names_out())

# Show the TF-IDF Matrix
print("\nTF-IDF Representation:")
print(X_tfidf.toarray())

Vocabulary: ['also' 'amazing' 'and' 'but' 'fun' 'is' 'just' 'learning' 'not'
 'powerful' 'python']

 TF-IDF Representation:
[[0.         0.57292883 0.57292883 0.         0.338381   0.338381
  0.         0.         0.         0.         0.338381  ]
 [0.40667606 0.         0.         0.40667606 0.24018943 0.24018943
  0.40667606 0.         0.40667606 0.40667606 0.24018943]
 [0.         0.         0.         0.         0.41285857 0.41285857
  0.         0.69903033 0.         0.         0.41285857]]


#Word2Vec

In [ ]:
!pip install gensim

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 3.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.6/60.6 kB 3.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 26.6/26.6 MB 56.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.0/18.0 MB 68.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 38.2/38.2 MB 13.4 MB/s eta 0:00:00
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.2
    Uninstalling numpy-2.0.2:
      Successfully uninstalled numpy-2.0.2
  Attempting uninstall: scipy
    Found existing installation: scipy 1.16.1
    Uninstalling scipy-1.16.1:
      Successfully uninstalled scipy-1.16.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
opencv-python-headless 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatib

In [ ]:
# Importing Important Libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import re
from gensim.models import Word2Vec

In [ ]:
import kagglehub
from kagglehub import KaggleDatasetAdapter

dataset = pd.read_csv("/kaggle/input/covid-19-nlp-text-classification/Corona_NLP_train.csv", encoding='ISO-8859-1')

print("First 5 records:", dataset.head())

First 5 records:    UserName  ScreenName   Location     TweetAt  \
0      3799       48751     London  16-03-2020   
1      3800       48752         UK  16-03-2020   
2      3801       48753  Vagabonds  16-03-2020   
3      3802       48754        NaN  16-03-2020   
4      3803       48755        NaN  16-03-2020   

                                       OriginalTweet           Sentiment  
0  @MeNyrbie @Phil_Gahan @Chrisitv https://t.co/i...             Neutral  
1  advice Talk to your neighbours family to excha...            Positive  
2  Coronavirus Australia: Woolworths to give elde...            Positive  
3  My food stock is not the only one which is emp...            Positive  
4  Me, ready to go at supermarket during the #COV...  Extremely Negative  


In [ ]:
texts=[]
for i in range(0,len(dataset)):
  text = re.sub('[^a-zA-Z]' , ' ', dataset['OriginalTweet'][i])
  text = text.lower()
  text = text.split()
  x = len(text) if text.count('https') ==0  else text.index('https')
  text = text[: x ]
  text = [t for t in text if not t=='https']
  text = ' '.join(text)
  texts.append(text)

sentences = [line.split() for line in texts]

w2v = Word2Vec(sentences, vector_size=100, window=5, workers=4, epochs=10, min_count=5)

print(sentences[20:25])

[['with', 'nations', 'inficted', 'with', 'covid', 'the', 'world', 'must', 'not', 'play', 'fair', 'with', 'china', 'goverments', 'must', 'demand', 'china', 'adopts', 'new', 'guilde', 'lines', 'on', 'food', 'safty', 'the', 'chinese', 'goverment', 'is', 'guilty', 'of', 'being', 'irosponcible', 'with', 'life', 'on', 'a', 'global', 'scale'], [], ['we', 'have', 'amazing', 'cheap', 'deals', 'for', 'the', 'covid', 'going', 'on', 'to', 'help', 'you', 'trials', 'monthly', 'yearly', 'and', 'resonable', 'prices', 'subscriptions', 'just', 'dm', 'us', 'bestiptv', 'iptv', 'service', 'iptv', 'iptvdeals', 'cheap', 'iptv', 'football', 'hd', 'movies', 'adult', 'cinema', 'hotmovies', 'iptvnew', 'iptv', 'adult'], ['we', 'have', 'amazing', 'cheap', 'deals', 'for', 'the', 'covid', 'going', 'on', 'to', 'help', 'you', 'trials', 'monthly', 'yearly', 'and', 'resonable', 'prices', 'subscriptions', 'just', 'dm', 'us', 'bestiptv', 'iptv', 'service', 'iptv', 'iptvdeals', 'cheap', 'iptv', 'football', 'hd', 'movies', 

In [ ]:
words = list(w2v.wv.index_to_key)
print(words)

print( w2v.wv['computer'] )

['the', 'to', 'and', 'of', 'covid', 'a', 'in', 'coronavirus', 'for', 'is', 'are', 'i', 'you', 'on', 's', 'this', 'prices', 'at', 'it', 'food', 'supermarket', 'we', 'store', 'that', 'with', 'grocery', 'have', 'as', 'be', 'people', 't', 'from', 'amp', 'all', 'can', 'consumer', 'your', 'not', 'will', 'they', 'my', 'our', 'up', 'out', 'has', 'or', 'by', 'more', 'but', 'shopping', 'if', 'online', 'how', 'their', 'during', 'pandemic', 'so', 'now', 'no', 'what', 'get', 'about', 'who', 'need', 'workers', 'panic', 'just', 'there', 'us', 'do', 'like', 'time', 'sanitizer', 'home', 'was', 'an', 'demand', 'go', 'when', 'some', 'help', 'hand', 'stock', 'don', 're', 'going', 'one', 'm', 'me', 'here', 'due', 'buying', 'been', 'oil', 'new', 'crisis', 'please', 'work', 'them', 'after', 'other', 'toilet', 'because', 'only', 'these', 'should', 'toiletpaper', 'than', 'paper', 'today', 'over', 'stay', 'local', 'retail', 'keep', 'buy', 'stores', 'many', 'shelves', 'still', 'being', 'make', 'delivery', 'those

# Glove

In [ ]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("danielwillgeorge/glove6b100dtxt")

print("Path to dataset files:", path)

Path to dataset files: /kaggle/input/glove6b100dtxt


## Loading GloVe Vectors in Python

In [ ]:
import numpy as np

def load_glove_model(glove_file):
    """Loads GloVe word vectors from a text file."""
    word_vectors = {}
    with open(glove_file, 'r', encoding='utf-8') as f:
        for line in f:
            parts = line.split()
            word = parts[0]
            vector = np.array([float(val) for val in parts[1:]])
            word_vectors[word] = vector
    return word_vectors

# Replace 'path/to/your/glove.6B.100d.txt' with the actual path
glove_model = load_glove_model('/kaggle/input/glove6b100dtxt/glove.6B.100d.txt')

# Using the Embeddings
word = "example"
if word in glove_model:
    embedding = glove_model[word]
    print(f"Embedding for '{word}':\n{embedding}")
else:
    print(f"'{word}' not found in GloVe vocabulary.")



Embedding for 'example':
[-0.12617    0.61724    0.22581    0.39868    0.16111    0.1523
 -0.14715   -0.29447   -0.27348   -0.13753   -0.20898   -0.73436
  0.14144    0.15048    0.09179    0.018613   0.22539    0.15979
 -0.16935    0.42716    0.042284  -0.3477    -0.11413    0.12222
 -0.025027  -0.20805   -0.067264  -0.2956    -0.30807   -0.32903
  0.19059    0.77141   -0.19332   -0.31069    0.26745    0.32231
  0.2065     0.10497    0.49425   -0.38322   -0.12802   -0.069906
 -0.14828    0.085369  -0.18141    0.14688    0.60968   -0.21131
 -0.29148   -0.52773    0.59508    0.017369   0.15342    0.81925
 -0.20643   -2.0378    -0.11884   -0.16826    1.5288     0.15756
 -0.4994     0.39305    0.12672   -0.10968    1.3671    -0.21006
  0.15684    0.0063801  0.43836   -0.18765   -0.29088    0.18619
  0.085402   0.13985    0.40794   -0.14811    0.26702   -0.19142
 -0.6189     0.0091217  0.34971   -0.24079   -0.52476   -0.25071
 -1.5681     0.22101    0.046796  -0.62616   -0.043358  -0.42865


# Calculating Word Similarity (Cosine Similarity)

In [ ]:
from scipy.spatial.distance import cosine

def get_word_similarity(word1, word2, model):
    """Calculates cosine similarity between two words using GloVe embeddings."""
    if word1 in model and word2 in model:
        vec1 = model[word1]
        vec2 = model[word2]
        similarity = 1 - cosine(vec1, vec2)
        return similarity
    else:
        return None

similarity = get_word_similarity("king", "queen", glove_model)
if similarity is not None:
    print(f"Similarity between 'king' and 'queen': {similarity}")

Similarity between 'king' and 'queen': 0.7507690793623847


# FastText

In [ ]:
!pip install fasttext

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.4/73.4 kB 2.0 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Using cached pybind11-3.0.1-py3-none-any.whl.metadata (10.0 kB)
Using cached pybind11-3.0.1-py3-none-any.whl (293 kB)
  Created wheel for fasttext: filename=fasttext-0.9.3-cp312-cp312-linux_x86_64.whl size=4498214 sha256=adb9d8da4d76c17f004d864f531876b0f6eec45930237309a0332acc00da0757
  Stored in directory: /root/.cache/pip/wheels/20/27/95/a7baf1b435f1cbde017cabdf1e9688526d2b0e929255a359c6
Successfully built fasttext


In [ ]:
# Installing and Importing FastText
import fasttext
import os

# Creating Training Data
def create_sample_data():
    # Sample sentences for training
    sentences = [
        "The king rules the kingdom",
        "The queen helps the king",
        "Running is good exercise",
        "The runner runs fast",
        "Walking is healthy activity",
        "The walker walks slowly",
        "Reading books is fun",
        "The reader reads daily"
    ]

    # Save to text file (one sentence per line)
    with open('training_data.txt', 'w') as f:
        for sentence in sentences:
            f.write(sentence.lower() + '\n')  # Convert to lowercase

    print("Training data created in 'training_data.txt'")

create_sample_data()

Training data created in 'training_data.txt'


In [ ]:
# Training a Basic FastText Model
def train_simple_model():
    # Train skipgram model (predicts context from target word)
    model = fasttext.train_unsupervised(
        'training_data.txt',    # Input file
        model='skipgram',
        dim=50,                 # Embedding dimension
        epoch=10,               # Number of training iterations
        minCount=1,             # Minimum word frequency
        minn=3,                 # Minimum character n-gram length
        maxn=6                  # Maximum character n-gram length
    )

    model.save_model('word_vectors.bin')
    print("Model trained and saved as 'word_vectors.bin'")
    return model

model = train_simple_model()

Model trained and saved as 'word_vectors.bin'


In [ ]:
# Getting Word Vectors
def get_word_embeddings(model):
    king_vector = model.get_word_vector('king')
    print(f"Vector for 'king': {king_vector[:5]}...")
    print(f"Vector shape: {king_vector.shape}")

    kingdom_vector = model.get_word_vector('kingdom')
    print(f"Vector for 'kingdom' (OOV): {kingdom_vector[:5]}...")

    return king_vector, kingdom_vector

king_vec, kingdom_vec = get_word_embeddings(model)

Vector for 'king': [-0.0001826  -0.00033079  0.0004302   0.00088911 -0.00164602]...
Vector shape: (50,)
Vector for 'kingdom' (OOV): [ 0.00122273  0.00092931 -0.00018005 -0.00013839 -0.00051276]...


In [ ]:
# Finding Similar Words
def find_similar_words(model, word, k=3):
    print(f"\nWords similar to '{word}':")
    try:
        neighbors = model.get_nearest_neighbors(word, k)
        for i, (similarity, similar_word) in enumerate(neighbors, 1):
            print(f"{i}. {similar_word}: {similarity:.4f}")
    except Exception as e:
        print(f"Error: {e}")

find_similar_words(model, 'king')
find_similar_words(model, 'running')


Words similar to 'king':
1. walks: 0.2693
2. running: 0.1971
3. queen: 0.1912

Words similar to 'running':
1. runner: 0.4778
2. the: 0.3344
3. runs: 0.2653
